
###

POST http://localhost:3000/pedidos
Content-Type: application/json

{
  "data": "2026-06-11",
  "cliente_id": "3",
  "condicao_pagamento_id": "2",
  "forma_pagamento_id": "2",
   "prazo_entrega": "2026-07-10"
}



###
GET  http://localhost:3000/pedidos/

###
GET  http://localhost:3000/pedidos/1

###
DELETE http://localhost:3000/pedidos/7
