###

POST http://localhost:3000/clientes
Content-Type: application/json

{
  "nome": "Hide",
  "endereco": "whithe chapel",
  "bairro": "jkhyt",
  "cep": "20546575",
   "cidade_id": "2",
  "cpf": "132.345.134567",
  "email": "HeryJekyll@",
  "telefone": "2786580",
  "observacoes": "20"
  
  
  
}



###
GET  http://localhost:3000/clientes/

###
GET  http://localhost:3000/clientes/1

###
DELETE http://localhost:3000/clientes/1
