###

POST http://localhost:3000/formas
Content-Type: application/json

{
  "descricao": "pix"
  
}


###
GET  http://localhost:3000/condicao/

###
GET  http://localhost:3000/condicao/1

###
DELETE http://localhost:3000/condicao/1
