###

POST http://localhost:3000/cidades
Content-Type: application/json

{
  "nome": "mg",
  "uf": "mg"
}


###
GET  http://localhost:3000/cidades/

###
GET  http://localhost:3000/cidades/1

###
DELETE http://localhost:3000/cidades/1
