###

POST http://localhost:3000/produtos
Content-Type: application/json

{
  "descricao": "bolo",
  "unidade": "um",
  "valor_unit": "14.50",
  "estoque": "20"
  
  
}


###
GET  http://localhost:3000/produtos/

###
GET  http://localhost:3000/produtos/1

###
DELETE http://localhost:3000/produtos/1
