###

POST http://localhost:3000/cidades
Content-Type: application/json

{
  "nome": "mg",
  "uf": "mg"
}

###

PUT http://localhost:3000/cidades/2
Content-Type: application/json

{
  "nome": "são paulo",
  "uf": "sp"
}

###
GET  http://localhost:3000/cidades/

###
GET  http://localhost:3000/cidades/1

###
DELETE http://localhost:3000/cidades/1
